server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:39610/railway
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect